import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import PageBody from "@/components/PageBody";
import PageHeader from "@/components/PageHeader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "PRANxt",
  description: "Generated by PRANxt",
};

export interface PageProps {
  children: React.ReactNode;
}

export default function RootLayout({
  children,
}: Readonly<PageProps>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PageHeader />
        <PageBody>
          {children}
        </PageBody>
      </body>
    </html>
  );
}
